FROM node:16-alpine as node
RUN mkdir -p /app
WORKDIR /app/client

COPY . /app/client

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

RUN cd /app/client
RUN npm install

EXPOSE 3005 

CMD ["npm", "start"]