version: "3.6"

services:
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_BASE_URL=http://217.182.171.139:3000
    container_name: front-spotify-handler-container
    restart: always
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - FRONT_REDIRECT_URI=http://217.182.171.139/login-redirect
      - SPOTIFY_CALLBACK=http://217.182.171.139:3000/auth/spotify/callback
      - HOST_URL=http://217.182.171.139:3000/
    container_name: back-spotify-handler-container
    restart: always
    links:
      - mongo
  mongo:
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
