version: '3.6'

services:
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - '3005:3005'
    environment:
      - NODE_ENV=dev
    volumes:
      - './client:/app/client'
    container_name: front-container
    restart: always
  backend:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - './server:/app/server'
    container_name: back-container
    restart: always
    links:
      - mongo
  mongo:
    image: mongo:4.0
    volumes:
      - './mongo/data:/data/db'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
