name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to VPS via SSH and build Docker Compose
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.VPS_USERNAME }}
          host: ${{ secrets.VPS_HOST }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd spotify-handler
            git pull
            sudo docker-compose --file docker-compose.prod.yml build

      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.VPS_USERNAME }}
          host: ${{ secrets.VPS_HOST }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd spotify-handler
            sudo docker-compose --file docker-compose.prod.yml up -d
