name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: Dreamer06

      - name: Go to the right folder
        run: cd spotify-handler

      - name: Git pull
        run: git pull

      - name: Build Docker Compose
        run: sudo docker-compose --file docker-compose.prod.yml build
