name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get -y install sshpass

      - name: Connect to VPS via SSH and build Docker Compose
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -tt ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd spotify-handler && git pull && sudo docker-compose --file docker-compose.prod.yml build"
      
      - name: Run Docker Compose
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -tt ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd spotify-handler && sudo docker-compose --file docker-compose.prod.yml up -d"
